### PR TITLE
FHS media handling

### LINKED ISSUE #640: FS.test_existing_manual_mount_point fails with --enable-fhs-media
Version: 2.8.2

Running the integration-test, I get the following failure
```
# src/tests/integration-test FS.test_existing_manual_mount_point
Testing installed system binaries
daemon path: /usr/lib/udisks2/udisksd
[ 1241.860207] scsi host2: scsi_debug: version 0188 [20180128]
[ 1241.860207]   dev_size_mb=61, opts=0x0, submit_queues=1, statistics=0
[ 1241.864009] scsi 2:0:0:0: Direct-Access     Linux    scsi_debug       0188 PQ: 0 ANSI: 7
[ 1241.867752] sd 2:0:0:0: Power-on or device reset occurred
[ 1241.869163] sd 2:0:0:0: Attached scsi generic sg1 type 0
[ 1241.876826] sd 2:0:0:0: [sda] 124928 512-byte logical blocks: (64.0 MB/61.0 MiB)
[ 1241.882342] sd 2:0:0:0: [sda] Write Protect is off
[ 1241.891543] sd 2:0:0:0: [sda] Write cache: enabled, read cache: enabled, supports DPO and FUA
[ 1241.990849] sd 2:0:0:0: [sda] Attached SCSI disk
[ 1242.099805] scsi host3: scsi_debug: version 0188 [20180128]
[ 1242.099805]   dev_size_mb=61, opts=0x0, submit_queues=1, statistics=0
[ 1242.108055] scsi 3:0:0:0: CD-ROM            Linux    scsi_debug       0188 PQ: 0 ANSI: 7
[ 1242.115024] sr 3:0:0:0: Power-on or device reset occurred
[ 1242.129799] sr 3:0:0:0: [sr1] scsi-1 drive
[ 1242.131448] sr 3:0:0:0: Attached scsi generic sg2 type 5
Set up test device: r/w: /dev/sda, r/o: /dev/sr1
test_existing_manual_mount_point (__main__.FS)
fs: does not reuse existing manual mount point ... [ 1243.867960] EXT4-fs (sda): mounted filesystem with ordered data mode. Opts: (null)
[ 1244.113344] EXT4-fs (sda): mounted filesystem with ordered data mode. Opts: (null)
ERROR

======================================================================
ERROR: test_existing_manual_mount_point (__main__.FS)
fs: does not reuse existing manual mount point
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/tests/integration-test", line 786, in test_existing_manual_mount_point
    self.assertEqual(new_mount_path, mount_path + '1')
  File "/usr/lib/python3.7/unittest/case.py", line 839, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.7/unittest/case.py", line 1220, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.7/unittest/case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: '/media/root/udiskstest' != '/media/root/udiskstest1'
- /media/root/udiskstest
+ /media/root/udiskstest1
?                       +


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/tests/integration-test", line 788, in test_existing_manual_mount_point
    os.rmdir(mount_path)
FileNotFoundError: [Errno 2] No such file or directory: '/media/root/udiskstest'

----------------------------------------------------------------------
Ran 1 test in 1.398s

FAILED (errors=1)
[ 1244.286273] print_req_error: I/O error, dev sda, sector 544
[ 1244.288158] print_req_error: I/O error, dev sda, sector 544
[ 1244.290047] buffer_io_error: 87 callbacks suppressed
[ 1244.290049] Buffer I/O error on dev sda, logical block 68, async page read
[ 1244.294194] print_req_error: I/O error, dev sda, sector 544
[ 1244.295207] Buffer I/O error on dev sda, logical block 68, async page read
[ 1244.296442] print_req_error: I/O error, dev sda, sector 544
[ 1244.297443] Buffer I/O error on dev sda, logical block 68, async page read
[ 1244.303971] sd 2:0:0:0: [sda] Synchronizing SCSI cache
[ 1244.310028] Buffer I/O error on dev sda, logical block 68, async page read
```

### PR DESCRIPTION
**Pull request by tbzatek**
This could be little controversial since it ditches the systemd cleanup service, however I think I've covered all use cases more universal way in the `UDisksState` class. Please shout if I missed something important.

This will hopefully fix #640 and I've modified the integration test testcase to make the issue more pronounced (when half of this PR is used).

Some reasons to ditch the systemd service are noted in d0d2ac2b3a33eccd9ed23e58da0bfd93628d78ca, there are couple more remarks:
-  also fixes failures with the cleanup service setup reported by running d-bus tests on udisks compiled with FHS enabled:
```
(lt-udisksd:13863): udisks-WARNING **: 18:28:17.730: Failed to setup systemd-based mount point cleanup: Process reported exit code 5: Failed to start clean-mount-point@media-root-c2a13063\x2d131a\x2d497b\x2da10e\x2d60101c880b0a.service: Unit clean-mount-point@media-root-c2a13063\x2d131a\x2d497b\x2da10e\x2d60101c880b0a.service not found.

(lt-udisksd:13863): udisks-WARNING **: 18:31:37.298: Failed to setup systemd-based mount point cleanup: Process reported exit code 5: Failed to start clean-mount-point@media-TEST_iso9660.service: Unit clean-mount-point@media-TEST_iso9660.service not found.
```
- haven't looked for the reason behind this error, presumably timing issue where the mount(point) was gone before the service setup has finished. Not even sure what mess this half-setup service left behind. It's gone now, so don't bother.
- also fixes test_80_filesystem.test_mount_fstab race conditions leading to "Device or resource busy" error during `shutil.rmtree()`

Heavy testing needed (as usual...)

### CODE REVIEW

**Comment by tbzatek** [comment]
I've split-out the `UDisksMountMonitor` changes to a separate branch (not yet published) as I found several race conditions and issues with that code. The whole class needs rework, many filesystem-related random failures from `dbus-tests` are caused by stall cache information.

FYI, the commit e86ea628177c3ea67525175f73a143e15ea74d67 introduced yet another issue, related to `UDisksMountMonitor`. It's not as exposed during typical (desktop) use, in fact all the described race conditions are rather hard to hit and mostly affects high-traffic scripts. Still I feel this can be fixed.

Let's focus just on `UDisksState` here.

**Comment by tbzatek** [comment]
Rebased, added couple of changes stashed locally.
Ready to review.

**Comment by tbzatek** [comment]
Hmm, seems like the daemon is having trouble registering new mount during LUKS tests... I'll have a look at that.

**Comment by tbzatek** [comment]
I've got another series of patches ready that build on top of this work but wanted to keep them separate from this one. Will post that once this is merged since GitHub apparently doesn't allow stacking pull requests on top of each other.

File: src/udisksstate.c [hunk 1]
```diff
@@ -77,6 +77,17 @@
...
+ *           Contains only non-persistent mount points. This state file is typically stored on
+ *           a non-persistent filesystem.
+ *         </entry>
+ *       </row>
+ *       <row>
+ *         <entry><filename>/var/lib/udisks2/mounted-fs-persistent</filename></entry>
+ *         <entry>
+ *           Similar in contents and data structure to <filename>/run/udisks2/mounted-fs</filename>
+ *           except that only persistent mount points are stored there. This state file is
+ *           typically stored on a persistent filesystemA.
```
Comment (vojtechtrefny) [inline src/udisksstate.c]: _stored on a persistent  filesystem**A**._

File: src/udiskslinuxfilesystem.c [hunk 2]
```diff
@@ -1284,6 +1284,7 @@ is_system_managed (UDisksDaemon *daemon,
 
 static void trigger_mpoint_cleanup (const gchar *mount_point)
 {
+#ifdef HAVE_LIBSYSTEMD_LOGIN
```
Comment (vojtechtrefny) [inline src/udiskslinuxfilesystem.c]: You can remove this commit -- this function is being removed in 8f89e61636579c6284ba58439493a9c32f5caa97

File: src/udiskslinuxfilesystem.c [hunk 3]
```diff
@@ -1913,7 +1913,7 @@ handle_unmount (UDisksFilesystem      *filesystem,
                                          0,
                                          NULL);
 
-  if (!bd_fs_unmount (mount_point ? mount_point : udisks_block_get_device (block),
+  if (!bd_fs_unmount (udisks_block_get_device (block),
```
[the remark this answers is not in the document]
Comment (tbzatek) [reply src/udiskslinuxfilesystem.c]: Ah, right, I've completely forgot about the bind mounts case. After brief discussion with @vojtechtrefny we've agreed this is even more complicated. I'll ditch this commit and will deal with this separately - filed #712 instead.

I was even thinking about checking the `MountPoints` property for multiple entries and either unmount by mount point if multiple mounts or by device in case of a single mount. However that would be inherently racy the same way.

File: src/udiskslinuxfilesystem.c (hunk 2 above)
Comment (tbzatek) [reply src/udiskslinuxfilesystem.c]: Aaa, busted. Wanted to boost my commit stats a little bit...

File: src/udisksstate.c [hunk 4]
```diff
@@ -497,7 +509,12 @@ udisks_state_check_in_thread (UDisksState *state)
   /* Then go through all mounted filesystems and pass the
    * devices that we intend to clean...
    */
-  udisks_state_check_mounted_fs (state, devs_to_clean);
+  udisks_state_check_mounted_fs (state,
+                                 "mounted-fs",
```
[the remark this answers is not in the document]
Comment (tbzatek) [reply src/udisksstate.c]: Right, turned the strings into constants.

**Comment by tbzatek** [comment]
Thanks for the comments. Rebased and cleaned up.
